import 'clock_positions.dart';

const double pi = 3.1415926535897932;
const double halfPi = (pi / 2);

const Map<String, List<List>> numbersSequence = {
  '0': [
    [
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner
    ],
    [
      ClockPositions.vertical,
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.vertical,
      ClockPositions.vertical,
      ClockPositions.off,
      ClockPositions.vertical,
      ClockPositions.vertical
    ],
    [
      ClockPositions.vertical,
      ClockPositions.vertical,
      ClockPositions.off,
      ClockPositions.vertical,
      ClockPositions.vertical
    ],
    [
      ClockPositions.vertical,
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner
    ],
  ],
  '1': [
    [
      ClockPositions.off,
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.off
    ],
    [
      ClockPositions.off,
      ClockPositions.bottomLeftCorner,
      ClockPositions.topRightCorner,
      ClockPositions.vertical,
      ClockPositions.off
    ],
    [
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.vertical,
      ClockPositions.vertical,
      ClockPositions.off
    ],
    [
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.vertical,
      ClockPositions.vertical,
      ClockPositions.off
    ],
    [
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.vertical,
      ClockPositions.vertical,
      ClockPositions.off
    ],
    [
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.bottomLeftCorner,
      ClockPositions.bottomRightCorner,
      ClockPositions.off
    ],
  ],
  '2': [
    [
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.vertical,
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner
    ],
    [
      ClockPositions.vertical,
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner
    ],
  ],
  '3': [
    [
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner
    ],
  ],
  '4': [
    [
      ClockPositions.topLeftCorner,
      ClockPositions.topRightCorner,
      ClockPositions.off,
      ClockPositions.topLeftCorner,
      ClockPositions.topRightCorner
    ],
    [
      ClockPositions.vertical,
      ClockPositions.vertical,
      ClockPositions.off,
      ClockPositions.vertical,
      ClockPositions.vertical
    ],
    [
      ClockPositions.vertical,
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.vertical,
      ClockPositions.vertical
    ],
    [
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.bottomLeftCorner,
      ClockPositions.bottomRightCorner
    ],
  ],
  '5': [
    [
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner
    ],
    [
      ClockPositions.vertical,
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner
    ],
    [
      ClockPositions.vertical,
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner
    ],
  ],
  '6': [
    [
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner
    ],
    [
      ClockPositions.vertical,
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner
    ],
    [
      ClockPositions.vertical,
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner
    ],
    [
      ClockPositions.vertical,
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.vertical,
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner
    ],
  ],
  '7': [
    [
      ClockPositions.off,
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
    ],
    [
      ClockPositions.off,
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.topLeftCorner,
      ClockPositions.bottomRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.bottomLeftCorner,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.vertical,
      ClockPositions.vertical
    ],
    [
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.off,
      ClockPositions.bottomLeftCorner,
      ClockPositions.bottomRightCorner
    ],
  ],
  '8': [
    [
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner
    ],
    [
      ClockPositions.vertical,
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.vertical,
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.vertical,
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.vertical,
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner
    ],
  ],
  '9': [
    [
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner
    ],
    [
      ClockPositions.vertical,
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.vertical,
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.topRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.topLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner,
      ClockPositions.vertical
    ],
    [
      ClockPositions.bottomLeftCorner,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.horizontal,
      ClockPositions.bottomRightCorner
    ],
  ],
};
